---
- name: Add new user with SSH key
  ansible.builtin.user:
    name: ansible
    state: present
    shell: /bin/bash
    groups: sudo

- name: Add SSH key for the new user
  ansible.builtin.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

